name: LevelSystem
version: '${project.version}'
main: com.yourname.LevelSystem
api-version: '1.21'
author: GuardTeam-ysxiaoyu
description: 生存等级
softdepend: [PlaceholderAPI]
folia-supported: false  # Leaf基于Paper，不支持Folia

commands:
  level:
    description: 等级系统主命令
    usage: /<command> [reload|info|set <玩家> <级> <段> <值>]
    aliases: [lv, dengji, ls]

permissions:
  levelsystem.admin:
    description: 管理员权限
    default: op
  levelsystem.use:
    description: 使用基础命令
    default: true
  levelsystem.reload:
    description: 重载配置权限
    default: op